import java.util.*;

/**
 * Class to count frequencies of the words generated by an iterator.
 *
 * @author CS2510
 * @version 11-09-2013
 */
public class WordCounter {
  ArrayList<Word> list;


  /**
   * The default constructor
   */
  public WordCounter() {
    list = new ArrayList<>();
  }

  /**
   * record the words generated by the given iterator
   *
   * @param it the given iterator over the input text
   */
  public void countWords(Iterator<Word> it) {
    while (it.hasNext()) {
      Word w = it.next();
      if (list.contains(w)) {
        int i = list.indexOf(w);
        list.get(i).counter++;
      } else {
        list.add(w);
      }
    }
  }

  /**
   * Count the number of different words in this Counter
   *
   * @return the count of different words in this Counter
   */
  public int words() {
    /* ... FILL IN ... */
    return list.size();
  }

  /**
   * Print the words and their frequencies for the top n words
   *
   * @param n the number of words to print
   */
  void printWords(int n) {
    Comparator<Word> wc = new WordsByFreq();
    list.sort(wc);
    StringBuilder result = new StringBuilder();
    for (int i = 0; i < n; i++) {
      result.append(list.get(i).toString());
    }
    System.out.println("The top n words are :" + result.toString());


  }
}
